// Action Types

// Auth
export const AUTH_LOGIN = "AUTH_LOGIN"
export const AUTH_LOGOUT = "AUTH_LOGOUT"
export const AUTH_REGISTER = "AUTH_REGISTER"
export const AUTH_UPDATE_PROFILE = "AUTH_UPDATE_PROFILE"
export const AUTH_ERROR = "AUTH_ERROR"
export const AUTH_LOADING = "AUTH_LOADING"

// Books
export const BOOKS_FETCH_ALL = "BOOKS_FETCH_ALL"
export const BOOKS_FETCH_FEATURED = "BOOKS_FETCH_FEATURED"
export const BOOKS_FETCH_BY_ID = "BOOKS_FETCH_BY_ID"
export const BOOKS_SEARCH = "BOOKS_SEARCH"
export const BOOKS_FETCH_BY_GENRE = "BOOKS_FETCH_BY_GENRE"
export const BOOKS_ADD = "BOOKS_ADD"
export const BOOKS_UPDATE = "BOOKS_UPDATE"
export const BOOKS_DELETE = "BOOKS_DELETE"
export const BOOKS_ERROR = "BOOKS_ERROR"
export const BOOKS_LOADING = "BOOKS_LOADING"

// Cart
export const CART_ADD_ITEM = "CART_ADD_ITEM"
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"
export const CART_UPDATE_QUANTITY = "CART_UPDATE_QUANTITY"
export const CART_CLEAR = "CART_CLEAR"
export const CART_APPLY_COUPON = "CART_APPLY_COUPON"
export const CART_REMOVE_COUPON = "CART_REMOVE_COUPON"

// Forums
export const FORUMS_FETCH_CATEGORIES = "FORUMS_FETCH_CATEGORIES"
export const FORUMS_FETCH_SUBFORUMS = "FORUMS_FETCH_SUBFORUMS"
export const FORUMS_FETCH_TOPICS = "FORUMS_FETCH_TOPICS"
export const FORUMS_FETCH_RECENT_TOPICS = "FORUMS_FETCH_RECENT_TOPICS"
export const FORUMS_FETCH_TOPIC = "FORUMS_FETCH_TOPIC"
export const FORUMS_CREATE_TOPIC = "FORUMS_CREATE_TOPIC"
export const FORUMS_CREATE_REPLY = "FORUMS_CREATE_REPLY"
export const FORUMS_LIKE_REPLY = "FORUMS_LIKE_REPLY"
export const FORUMS_UNLIKE_REPLY = "FORUMS_UNLIKE_REPLY"
export const FORUMS_BOOKMARK_TOPIC = "FORUMS_BOOKMARK_TOPIC"
export const FORUMS_UNBOOKMARK_TOPIC = "FORUMS_UNBOOKMARK_TOPIC"
export const FORUMS_ERROR = "FORUMS_ERROR"
export const FORUMS_LOADING = "FORUMS_LOADING"

// Communities
export const COMMUNITIES_FETCH_ALL = "COMMUNITIES_FETCH_ALL"
export const COMMUNITIES_FETCH_JOINED = "COMMUNITIES_FETCH_JOINED"
export const COMMUNITIES_FETCH_BY_ID = "COMMUNITIES_FETCH_BY_ID"
export const COMMUNITIES_JOIN = "COMMUNITIES_JOIN"
export const COMMUNITIES_LEAVE = "COMMUNITIES_LEAVE"
export const COMMUNITIES_CREATE = "COMMUNITIES_CREATE"
export const COMMUNITIES_ERROR = "COMMUNITIES_ERROR"
export const COMMUNITIES_LOADING = "COMMUNITIES_LOADING"

// Notifications
export const NOTIFICATION_ADD = "NOTIFICATION_ADD"
export const NOTIFICATION_REMOVE = "NOTIFICATION_REMOVE"
export const NOTIFICATION_CLEAR_ALL = "NOTIFICATION_CLEAR_ALL"

